<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open Swag Labslogin using standart_acco_21424a</name>
   <tag></tag>
   <elementGuidId>5ac4f002-ae9c-454c-b830-8a5393b57c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scroll-container-default']/div/div/div/div[2]/div/div[2]/div[10]/div[7]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.E_znYACg.CTYilBmu.gjzUOZZj > div.fderA03N.hu8TEfLP.kr-slate-editor.kr-slate-editor-is-directly-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba97bbb5-2bd5-46ee-a767-54db4e64a334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fderA03N hu8TEfLP kr-slate-editor kr-slate-editor-is-directly-focused</value>
      <webElementGuid>ecebc296-c6cc-42de-83e8-ff0a27da9418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-editable-id</name>
      <type>Main</type>
      <value>root</value>
      <webElementGuid>00cf61c5-df46-4aa8-9ef0-f93c7159698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7820d1d7-1dfe-45c5-962a-3646d322e8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ca3c792-5c9b-4508-b77a-04e7fdfd624f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3212afea-d9ea-4949-a032-1355ca4c3723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-coda-ui-id</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>047c513a-889b-40ae-9f2e-1d978636a31d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Swag Labslogin using standart_accountClick LoginAdd item to chartInsert First Name,Last Name,and Zip CodeClick CheckoutClick Finish</value>
      <webElementGuid>1d981703-c8ea-4902-bf31-dd1e7c1cad5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scroll-container-default&quot;)/div[@class=&quot;F2clv2Bn w9mOGWSw YDGNwFiI&quot;]/div[@class=&quot;VuI2FvsR&quot;]/div[@class=&quot;fTZaMvkW&quot;]/div[@class=&quot;UigI0tfj&quot;]/div[@class=&quot;jIXZS52Z cbzMZ6zH active MwyAQHN6 ZRrDROYM nlxOrxDB gjzUOZZj&quot;]/div[@class=&quot;s_3L6O5h kr-row-container qs2GL70L&quot;]/div[@class=&quot;hVp9At_N kr-row&quot;]/div[@class=&quot;kr-cell selectable NaIjZvs0 ioDNY_K4 gjzUOZZj TpNQ0boZ EB_mGMKO X1GIGD37 wSCT8ojG&quot;]/div[@class=&quot;UigI0tfj&quot;]/div[@class=&quot;UigI0tfj&quot;]/div[@class=&quot;E_znYACg CTYilBmu gjzUOZZj&quot;]/div[@class=&quot;fderA03N hu8TEfLP kr-slate-editor kr-slate-editor-is-directly-focused&quot;]</value>
      <webElementGuid>3b252d6d-b50e-4260-bd1e-75dc5f559f3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll-container-default']/div/div/div/div[2]/div/div[2]/div[10]/div[7]/div/div/div/div</value>
      <webElementGuid>23ca3510-b9e1-47bb-9010-d94207205dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pass = secret_sauce'])[6]/following::div[5]</value>
      <webElementGuid>88ce5c5c-36ce-4665-bce9-7fd409ad34a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[7]/div/div/div/div</value>
      <webElementGuid>6600afb3-201d-4457-b583-5fce25602878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Open Swag Labslogin using standart_accountClick LoginAdd item to chartInsert First Name,Last Name,and Zip CodeClick CheckoutClick Finish' or . = 'Open Swag Labslogin using standart_accountClick LoginAdd item to chartInsert First Name,Last Name,and Zip CodeClick CheckoutClick Finish')]</value>
      <webElementGuid>c221fc4d-595b-48c7-8455-92fbd3eece25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
